import {
    Box,
    Braces,
    Bug,
    Cloud,
    Code,
    Cpu,
    Database,
    FileCode2,
    FlaskConical,
    GitBranch,
    Globe,
    Layers,
    Palette,
    Puzzle,
    Rocket,
    Server,
    Settings,
    Shield,
    Sparkles,
    Terminal,
    Wrench,
    Zap,
    type LucideIcon,
} from "lucide-react";

export const TOOL_ICONS: Record<string, LucideIcon> = {
    code: Code,
    terminal: Terminal,
    database: Database,
    globe: Globe,
    wrench: Wrench,
    settings: Settings,
    fileCode: FileCode2,
    braces: Braces,
    box: Box,
    cloud: Cloud,
    cpu: Cpu,
    bug: Bug,
    gitBranch: GitBranch,
    flask: FlaskConical,
    rocket: Rocket,
    shield: Shield,
    sparkles: Sparkles,
    layers: Layers,
    server: Server,
    palette: Palette,
    puzzle: Puzzle,
    zap: Zap,
};

export const TOOL_ICON_NAMES = Object.keys(TOOL_ICONS);
