import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import { Bell, Bookmark, Heart, MessageCircle, MoreHorizontal, Plus, Search, Send } from "lucide-react-native";
import { ActivityIndicator, Image, Pressable, ScrollView, Text, View } from "react-native";
import { MediaViewer } from "@/components/MediaViewer";
import { Screen } from "@/components/Screen";
import { DiscoverPost, getDiscover, togglePostLike, togglePostSave } from "@/services/product";
import { en } from "@/i18n/en";
import { useAppTheme } from "@/theme/useAppTheme";

const filters = en.overview.filters;

export default function OverviewScreen() {
  const client = useQueryClient();
  const { colors } = useAppTheme();
  const discover = useQuery({ queryKey: ["discover"], queryFn: getDiscover });
  const updatePost = (id: string, update: (post: DiscoverPost) => DiscoverPost) => client.setQueryData<{ posts: DiscoverPost[]; creators: never[]; collections: never[] }>(["discover"], (old) => old ? { ...old, posts: old.posts.map((post) => post.id === id ? update(post) : post) } : old);
  const like = useMutation({ mutationFn: togglePostLike, onMutate: (id) => updatePost(id, (post) => ({ ...post, likedByMe: !post.likedByMe, likeCount: post.likeCount + (post.likedByMe ? -1 : 1) })), onSettled: () => void client.invalidateQueries({ queryKey: ["discover"] }) });
  const save = useMutation({ mutationFn: togglePostSave, onMutate: (id) => updatePost(id, (post) => ({ ...post, savedByMe: !post.savedByMe })), onSettled: () => void client.invalidateQueries({ queryKey: ["discover"] }) });

  return <Screen title="Overview" refreshing={discover.isRefetching} onRefresh={() => void discover.refetch()} action={<Pressable accessibilityRole="button" accessibilityLabel="Notifications" onPress={() => router.push("/notifications")} className="h-11 w-11 items-center justify-center rounded-xl bg-card"><Bell color={colors.foreground} size={21} /></Pressable>}>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerClassName="gap-2">{filters.map((filter, index) => <View key={filter} className={`min-h-10 flex-row items-center rounded-full border px-3 ${index === 0 ? "border-primary bg-primary" : "border-border bg-muted"}`}><Text className={`text-xs font-semibold ${index === 0 ? "text-white" : "text-muted-foreground"}`}>{filter}</Text></View>)}</ScrollView>
    <Pressable accessibilityRole="search" accessibilityLabel="Search creators, tools, and posts" onPress={() => router.push("/(tabs)/explore")} className="flex-row items-center gap-3 rounded-full border border-border bg-card px-4 py-3"><Search color={colors.mutedForeground} size={18} /><Text className="text-xs tracking-wide text-muted-foreground">Search creators, tools, posts...</Text></Pressable>
    {discover.isPending ? <ActivityIndicator color="#ed4b4b" /> : null}{discover.isError ? <Text accessibilityRole="alert" className="rounded-2xl bg-destructive/10 p-4 text-destructive">Could not load your feed.</Text> : null}
    {discover.data?.creators.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerClassName="gap-4 rounded-3xl px-1 py-2">{discover.data.creators.slice(0, 14).map((creator) => <Pressable accessibilityLabel={`Open ${creator.name ?? creator.tag ?? "creator"} profile`} onPress={() => creator.tag && router.push({ pathname: "/user/[tag]", params: { tag: creator.tag } })} key={creator.id} className="w-16 items-center gap-1.5">{creator.image ? <View className="rounded-full border-2 border-primary p-0.5"><Image source={{ uri: creator.image }} className="h-14 w-14 rounded-full" /></View> : <View className="h-14 w-14 items-center justify-center rounded-full border-2 border-primary bg-primary/10"><Text className="font-bold text-primary">{creator.name?.[0] ?? "?"}</Text></View>}<Text numberOfLines={1} className="w-full text-center text-[11px] text-muted-foreground">{creator.tag ?? creator.name ?? "creator"}</Text></Pressable>)}</ScrollView> : null}
    <View className="gap-4">{discover.data?.posts.map((post) => <View key={post.id} className="overflow-hidden rounded-3xl bg-card"><View className="flex-row items-center gap-2.5 px-4 py-3">{post.author.image ? <Image source={{ uri: post.author.image }} className="h-9 w-9 rounded-full" /> : <View className="h-9 w-9 items-center justify-center rounded-full bg-primary/10"><Text className="font-bold text-primary">{post.author.name?.[0] ?? "?"}</Text></View>}<View className="min-w-0 flex-1"><Text numberOfLines={1} className="text-sm font-semibold text-foreground">{post.author.name ?? "Creator"}</Text><Text numberOfLines={1} className="text-xs text-muted-foreground">@{post.author.tag ?? "user"}</Text></View><MoreHorizontal color="#6f6a87" size={19} /></View><Pressable onPress={() => router.push({ pathname: "/post/[id]", params: { id: post.id } })}>{post.media.length ? <MediaViewer media={post.media} height={360} /> : null}</Pressable><View className="gap-2 px-4 py-3"><View className="flex-row items-center justify-between"><View className="flex-row items-center gap-4"><Pressable accessibilityLabel="Like post" hitSlop={8} onPress={() => like.mutate(post.id)}><Heart size={22} color={post.likedByMe ? "#ed4b4b" : "#292d32"} fill={post.likedByMe ? "#ed4b4b" : "transparent"} /></Pressable><Pressable accessibilityLabel="Comment on post" hitSlop={8} onPress={() => router.push({ pathname: "/post/[id]", params: { id: post.id } })}><MessageCircle size={21} color="#292d32" /></Pressable><Pressable accessibilityLabel="Share post" hitSlop={8}><Send size={20} color="#292d32" /></Pressable></View><Pressable accessibilityLabel="Save post" hitSlop={8} onPress={() => save.mutate(post.id)}><Bookmark size={20} color={post.savedByMe ? "#ed4b4b" : "#292d32"} fill={post.savedByMe ? "#ed4b4b" : "transparent"} /></Pressable></View><Text className="text-sm font-semibold text-foreground">{post.likeCount.toLocaleString()} likes</Text>{post.caption ? <Text numberOfLines={2} className="text-sm leading-5 text-foreground"><Text className="font-semibold">{post.author.tag ?? post.author.name ?? "user"} </Text>{post.caption}</Text> : null}{post.commentCount ? <Text className="text-sm text-muted-foreground">View all {post.commentCount.toLocaleString()} comments</Text> : null}</View></View>)}</View>
    <Pressable accessibilityLabel="Create post" onPress={() => router.push("/new-post")} className="min-h-12 flex-row items-center justify-center gap-2 rounded-xl bg-primary"><Plus color="white" size={19} /><Text className="font-bold text-white">Create post</Text></Pressable>
  </Screen>;
}
