import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import { Bell, Bookmark, Heart, MessageCircle, Plus, Search } from "lucide-react-native";
import { ActivityIndicator, Image, Pressable, Text, View } from "react-native";
import { Screen } from "@/components/Screen";
import { DiscoverPost, getDiscover, togglePostLike, togglePostSave } from "@/services/product";

export default function OverviewScreen() {
  const client = useQueryClient(); const discover = useQuery({ queryKey: ["discover"], queryFn: getDiscover });
  const updatePost = (id: string, update: (post: DiscoverPost) => DiscoverPost) => client.setQueryData<{ posts: DiscoverPost[]; creators: never[]; collections: never[] }>(["discover"], (old) => old ? { ...old, posts: old.posts.map((post) => post.id === id ? update(post) : post) } : old);
  const like = useMutation({ mutationFn: togglePostLike, onMutate: (id) => updatePost(id, (post) => ({ ...post, likedByMe: !post.likedByMe, likeCount: post.likeCount + (post.likedByMe ? -1 : 1) })), onSettled: () => void client.invalidateQueries({ queryKey: ["discover"] }) });
  const save = useMutation({ mutationFn: togglePostSave, onMutate: (id) => updatePost(id, (post) => ({ ...post, savedByMe: !post.savedByMe })), onSettled: () => void client.invalidateQueries({ queryKey: ["discover"] }) });
  return <Screen title="Overview" subtitle="Discover what creators are building with." action={<Pressable accessibilityLabel="Notifications" onPress={() => router.push("/notifications")} className="h-11 w-11 items-center justify-center rounded-2xl bg-card"><Bell color="#292d32" size={21} /></Pressable>}>
    <Pressable onPress={() => router.push("/(tabs)/explore")} className="flex-row items-center gap-3 rounded-2xl bg-input px-4 py-3.5"><Search color="#6f6a87" size={19} /><Text className="text-sm text-muted-foreground">Search creators, tools, posts…</Text></Pressable>
    {discover.isPending ? <ActivityIndicator color="#ed4b4b" /> : null}{discover.isError ? <Text accessibilityRole="alert" className="rounded-2xl bg-destructive/10 p-4 text-destructive">Could not load your feed.</Text> : null}
    {discover.data?.creators.length ? <View className="gap-3"><Text className="text-lg font-bold text-foreground">Creators to follow</Text><View className="flex-row flex-wrap gap-3">{discover.data.creators.slice(0,4).map((creator) => <View key={creator.id} className="w-[47%] gap-2 rounded-3xl border border-border bg-card p-4">{creator.image ? <Image source={{ uri: creator.image }} className="h-12 w-12 rounded-2xl" /> : <View className="h-12 w-12 items-center justify-center rounded-2xl bg-primary/10"><Text className="font-bold text-primary">{creator.name?.[0] ?? "?"}</Text></View>}<Text numberOfLines={1} className="font-bold text-foreground">{creator.name ?? creator.tag ?? "Creator"}</Text><Text className="text-xs text-muted-foreground">{creator.followers} followers</Text></View>)}</View></View> : null}
    <View className="gap-4"><Text className="text-lg font-bold text-foreground">Latest posts</Text>{discover.data?.posts.map((post) => <View key={post.id} className="overflow-hidden rounded-3xl border border-border bg-card"><Pressable onPress={() => router.push({ pathname: "/post/[id]", params: { id: post.id } })}>{post.media[0]?.url ? <Image source={{ uri: post.media[0].url }} className="h-64 w-full bg-muted" resizeMode="cover" /> : null}<View className="gap-2 p-4"><Text className="font-bold text-foreground">{post.author.name ?? post.author.tag ?? "Creator"}</Text>{post.caption ? <Text numberOfLines={3} className="leading-5 text-foreground">{post.caption}</Text> : null}</View></Pressable><View className="flex-row gap-2 px-4 pb-4"><Pressable accessibilityLabel="Like post" onPress={() => like.mutate(post.id)} className="min-h-11 flex-row items-center gap-2 rounded-2xl bg-input px-3"><Heart size={18} color={post.likedByMe ? "#ed4b4b" : "#6f6a87"} fill={post.likedByMe ? "#ed4b4b" : "transparent"} /><Text className="text-foreground">{post.likeCount}</Text></Pressable><Pressable onPress={() => router.push({ pathname: "/post/[id]", params: { id: post.id } })} className="min-h-11 flex-row items-center gap-2 rounded-2xl bg-input px-3"><MessageCircle size={18} color="#6f6a87" /><Text className="text-foreground">{post.commentCount}</Text></Pressable><Pressable accessibilityLabel="Save post" onPress={() => save.mutate(post.id)} className="h-11 w-11 items-center justify-center rounded-2xl bg-input"><Bookmark size={18} color="#6f6a87" fill={post.savedByMe ? "#6f6a87" : "transparent"} /></Pressable></View></View>)}</View>
    <Pressable accessibilityLabel="Create post" onPress={() => router.push("/new-post")} className="min-h-14 flex-row items-center justify-center gap-2 rounded-2xl bg-primary"><Plus color="white" size={20} /><Text className="font-bold text-white">Create post</Text></Pressable>
  </Screen>;
}
