import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const toolKitFont = localFont({
    src: './fonts/toolkit-font.woff2',
    variable: '--font-toolkit',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${toolKitFont.variable}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
