import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import { Bookmark, Heart, MessageCircle, MoreHorizontal, Send } from "lucide-react-native";
import { useState } from "react";
import { Alert, Image, Pressable, Text, TextInput, View } from "react-native";
import { Screen } from "@/components/Screen";
import { createComment, deleteComment, deletePost, getComments, getPost, togglePostLike, togglePostSave, updatePost } from "@/services/product";
import { blockUser, reportContent } from "@/services/safety";

export default function PostScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const client = useQueryClient(); const [comment, setComment] = useState(""); const [editing, setEditing] = useState(false); const [caption, setCaption] = useState("");
  const post = useQuery({ queryKey: ["post", id], queryFn: () => getPost(id) }); const comments = useQuery({ queryKey: ["comments", id], queryFn: () => getComments(id) }); const refresh = () => { void client.invalidateQueries({ queryKey: ["post", id] }); void client.invalidateQueries({ queryKey: ["discover"] }); };
  const like = useMutation({ mutationFn: () => togglePostLike(id), onMutate: async () => { await client.cancelQueries({ queryKey: ["post", id] }); const old = client.getQueryData<{ post: NonNullable<typeof post.data>["post"] }>(["post", id]); if (old) client.setQueryData(["post", id], { post: { ...old.post, likedByMe: !old.post.likedByMe, likeCount: old.post.likeCount + (old.post.likedByMe ? -1 : 1) } }); return { old }; }, onError: (_e,_v,c) => { if (c?.old) client.setQueryData(["post",id],c.old); }, onSettled: refresh });
  const save = useMutation({ mutationFn: () => togglePostSave(id), onSuccess: refresh }); const send = useMutation({ mutationFn: () => createComment(id, comment.trim()), onSuccess: () => { setComment(""); void client.invalidateQueries({ queryKey: ["comments", id] }); refresh(); } });
  const item = post.data?.post;
  const menu = () => { if (!item) return; Alert.alert("Post actions", undefined, item.mine ? [{ text: "Edit", onPress: () => { setCaption(item.caption); setEditing(true); } }, { text: "Delete", style: "destructive", onPress: () => void deletePost(id).then(() => { void client.invalidateQueries({ queryKey: ["discover"] }); router.back(); }) }, { text: "Cancel", style: "cancel" }] : [{ text: "Report post", onPress: () => void reportContent("post", id, "other").then(() => Alert.alert("Report submitted")) }, { text: "Block creator", style: "destructive", onPress: () => void blockUser(item.author.id).then(() => router.back()) }, { text: "Cancel", style: "cancel" }]); };
  return <Screen title="Post" subtitle={item ? new Date(item.createdAt).toLocaleString() : "Loading…"} action={<Pressable accessibilityLabel="Post actions" onPress={menu} className="h-11 w-11 items-center justify-center rounded-2xl bg-card"><MoreHorizontal color="#292d32" size={21} /></Pressable>}>
    {item?.media[0]?.url ? <Image source={{ uri: item.media[0].url }} className="h-96 w-full rounded-3xl bg-muted" resizeMode="cover" /> : null}
    {item ? <View className="gap-3 rounded-3xl border border-border bg-card p-4"><Text className="font-bold text-foreground">{item.author.name ?? item.author.tag ?? "Creator"}</Text>{editing ? <><TextInput value={caption} onChangeText={setCaption} multiline className="min-h-24 rounded-2xl bg-input p-3 text-foreground" /><Pressable onPress={() => void updatePost(id, caption, item.tags, item.media.map((media) => ({ id: media.id, type: media.type }))).then(() => { setEditing(false); refresh(); })} className="min-h-11 items-center justify-center rounded-2xl bg-primary"><Text className="font-bold text-white">Save</Text></Pressable></> : <Text className="leading-6 text-foreground">{item.caption}</Text>}<View className="flex-row gap-3"><Pressable accessibilityLabel="Like post" onPress={() => like.mutate()} className="min-h-11 flex-row items-center gap-2 rounded-2xl bg-input px-4"><Heart color={item.likedByMe ? "#ed4b4b" : "#6f6a87"} fill={item.likedByMe ? "#ed4b4b" : "transparent"} size={19} /><Text className="text-foreground">{item.likeCount}</Text></Pressable><Pressable accessibilityLabel="Save post" onPress={() => save.mutate()} className="min-h-11 flex-row items-center gap-2 rounded-2xl bg-input px-4"><Bookmark color="#6f6a87" fill={item.savedByMe ? "#6f6a87" : "transparent"} size={19} /><Text className="text-foreground">Save</Text></Pressable></View></View> : null}
    <View className="gap-3"><View className="flex-row items-center gap-2"><MessageCircle color="#ed4b4b" size={20} /><Text className="text-lg font-bold text-foreground">Comments</Text></View>{comments.data?.comments.map((entry) => <Pressable onLongPress={() => entry.mine ? deleteComment(id, entry.id).then(() => client.invalidateQueries({ queryKey: ["comments", id] })) : reportContent("comment", entry.id, "other").then(() => Alert.alert("Report submitted"))} key={entry.id} className="rounded-2xl bg-card p-4"><Text className="font-semibold text-foreground">{entry.user.name ?? entry.user.tag ?? "Creator"}</Text><Text className="mt-1 text-foreground">{entry.content}</Text></Pressable>)}<View className="flex-row items-end gap-2 rounded-3xl border border-border bg-card p-2 pl-4"><TextInput value={comment} onChangeText={setComment} multiline placeholder="Add a comment…" className="min-h-12 flex-1 py-3 text-foreground" /><Pressable disabled={!comment.trim() || send.isPending} onPress={() => send.mutate()} className="h-12 w-12 items-center justify-center rounded-2xl bg-primary disabled:opacity-50"><Send color="white" size={18} /></Pressable></View></View>
  </Screen>;
}
